### ISSUE TITLE
Error with legacy / insecure mode?

### ISSUE THREAD

**Issue by l8nite** [attr-encrypted/encryptor#29]
Maybe I'm doing something obviously incorrect here? I'm copy/pasting the encrypted value.

```
irb(main):048:0> Encryptor.default_options
=> {:algorithm=>"aes-256-gcm", :auth_data=>"", :insecure_mode=>true, :hmac_iterations=>2000, :v2_gcm_iv=>true}
irb(main):049:0> Encryptor.encrypt(key: secret, value: 'foo')
=> "X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A"
irb(main):050:0> Encryptor.decrypt(key: secret, value: "X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A")
OpenSSL::Cipher::CipherError: unable to set AEAD tag
        from /home/sguth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/encryptor-3.0.0/lib/encryptor.rb:91:in `auth_tag='
        from /home/sguth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/encryptor-3.0.0/lib/encryptor.rb:91:in `crypt'
        from /home/sguth/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
        from (irb):50
        from /home/sguth/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
irb(main):051:0>
```

**Comment by l8nite** [comment]
This probably isn't a bug with `encryptor`, not sure what it is yet, but see this:

```
irb(main):064:0> x
=> "X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A"
irb(main):065:0> y = "X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A"
=> "X\xC6[>\xB6\x98\u0014\b+\x93\x86R\xAC\x94\x9Bɮ\xDD\u001A"
irb(main):066:0> x.bytes
=> [88, 198, 91, 62, 182, 152, 20, 8, 43, 147, 134, 82, 172, 148, 155, 201, 174, 221, 26]
irb(main):067:0> y.bytes
=> [88, 198, 91, 62, 182, 152, 20, 8, 43, 147, 134, 82, 172, 148, 155, 201, 174, 221, 26]
irb(main):068:0> y.to_s
=> "X\xC6[>\xB6\x98\u0014\b+\x93\x86R\xAC\x94\x9Bɮ\xDD\u001A"
irb(main):069:0> x.to_s
=> "X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A"
irb(main):070:0>
```

**Comment by l8nite** [comment]
Ah ha, looks like doing `"X\xC6[>\xB6\x98\x14\b+\x93\x86R\xAC\x94\x9B\xC9\xAE\xDD\x1A".force_encoding(Encoding::ASCII_8BIT)`  causes it to succeed.
